
<!DOCTYPE html>
<html lang="en">
	
	<head>
		
		<meta charset="utf-8">
		<title>Eventica Staff Company</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
		
		<!-- CSS -->
		<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'>
		<link rel="stylesheet" href="css/proyecto.css">
		<link rel="stylesheet" href="css/foundation-icons.css" />
		<script src="js/modernizr.custom.34978.js"></script>
		
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="shortcut icon" href="img/favicon.ico">
	</head>
	
	<body style="border-top: 3px solid #fff;">
		
		<!-- Header -->
		<div class="container">
			<div class="header row" style="border-bottom: 3px solid #f8f8f8;" >
				<div class="large-4 columns">
					<a href="index.php"><img src="img/logo4.png" style="width:90%;margin-top:10px;"></a>
				</div>
				<div class="tel-skype large-8 columns">
					<p align="right"><i class="step fi-telephone size-72"></i> Phone: 0039 123 45 679 </p>
				</div>
			</div>
		</div>
		
		
		<div class="row">
			<div class="container" style="background-color:#fff;">
				<div class="row" style="background-color:#fff;">
					<div class="large-10 large-offset-1 columns" style="background-color:#fff;">
						<div class="maia-article" role="article">
							<div class="maia-teleport" id="content"></div>
							<h1>Eventica Terms of Service</h1>
							<p>Last Revised: July 1st, 2015 </p>

							<p align="justify">These Terms of Service (this <b>"Agreement"</b>) is an agreement between you (<b>"you"</b>) and Eventica, Inc.and governs your use of the website located at  <a href="http:// www.EventicaTeam.com "> www.EventicaTeam.com </a>and the Services (as defined below) (the Site and Services collectively the <b>"Eventica Platform"</b>). Eventica may amend this Agreement at any time and effective upon publication on the Site. Your continued use of the Eventica Platform after the effective date of a revised version of this Agreement constitutes your acceptance of its terms.</p>

							<p align="justify">Certain features of the Eventica Platform may be subject to additional terms which will be posted on the Eventica Platform in connection with such features. All such additional terms are incorporated by reference into this Agreement. In the event of a conflict between the additional terms and any provision in this Agreement, the additional terms will prevail, but only with respect to the Service to which the additional terms apply.</p>

							<p align="justify">THIS AGREEMENT FORTH THE LEGALLY BINDING TERMS FOR YOUR USE OF THE EVENTICA PLATFORM. BY ACCESSING OR USING THE EVENTICA PLATFORM, YOU ARE ACCEPTING THESE TERMS AND YOU REPRESENT AND WARRANT THAT (1) YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THIS AGREEMENT (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT), (2) YOU ARE AT LEAST 18 YEARS OLD, AND (3) YOU HAVE THE RIGHT AND AUTHORITY TO ENTER INTO THIS AGREEMENT (ON BEHALF OF YOURSELF OR THE ENTITY THAT YOU REPRESENT). YOU MAY NOT ACCESS OR USE THE EVENTICA PLATFORM IF YOU ARE NOT AT LEAST 18 YEARS OLD. IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, YOU MAY NOT ACCESS OR USE THE EVENTICA PLATFORM.</p>

							<!--The Eventica Plataform-->
							<h2>1. THE EVENTICA PLATFORM</h2>
							<h3>1.1 The Eventica Platform</h3>
							<p align="justify">Eventica provides an online platform designed to connect businesses seeking to obtain freelance services, including advertising and event marketing services (each a <b>"Client"</b>) with freelancers who provide such services (each a <b>"Freelancer")</b> (the <b>"Services"</b>).  Through the Services, Clients post advertising and marketing Events (the "Events") through the Site and Freelancers may review, pursue, submit for and accept Events posted and/or requested by Clients.  Freelancers have access to the Site to create and post profiles and respond to and/or accept Events posted by Clients.  When a Freelancer accepts a Project posted by a Client, then the terms and conditions for such Project, including the provision of Services thereto, shall be subject to the  Standard Project Terms (as defined herein), except to the extent otherwise modified in the stated terms and conditions of a particular Project posted by a Client.  Upon a Freelancer’s satisfactory performance of a Project, the Client submits payment through the Site for the benefit of the Freelancer and Eventica facilitates the Client’s payment to Freelancers on behalf of the Client.  Eventica’s services are limited to providing and maintaining a platform to enable and facilitate communication, connection, engagement and payment between Clients and Freelancers for the fulfillment of the Project. Unless expressly stated within the Services, Eventica’s responsibilities are limited to facilitating the availability of the Eventica Platform. Clients and Freelancers (and not Eventica) are solely responsible for any interaction between themselves, provided, however, that the Services may facilitate communications between Clients and Freelancers.</p>
							<p align="justify">Eventica grants you a non-transferable, non-exclusive, right to access the Site and use the Services for your personal and professional use, subject at all times to the terms of this Agreement including the restrictions on use, the acceptable use provisions and the our right to remove your Content (as defined below) or suspend access to your Account (as defined below) at our discretion at any time. You may not, however, use the Services on behalf of any third party without our consent.</p>
							<p align="justify">Subject to the terms and conditions herein and in consideration of the rights to use the Service granted by Eventica to you, Eventica grants you a personal, revocable, limited, non-transferable, non-sublicenseable license to use the App on either (1) any iPhone, iPad, or iPod Touch that you own or control, or (2) any Android-enabled mobile device that you own or control. With respect to any App accessed through or downloaded from the Apple App Store, Google Chrome Web Store, Google Play marketplace, or any similar store or marketplace (each, an <b>"App Store"</b> and references to an App Store include the corporate entity and its subsidiaries making such App Store available to you), you agree to comply with all applicable third party terms of the relevant App Store (e.g. Apple App Store’s "Usage Rules") (the <b>"Usage Rules"</b>).</p>
							<p align="justify">YOUR USE OF THE EVENTICA PLATFORM CONSTITUTES YOUR ACKNOWLEDGMENT THAT EVENTICA DOES NOT ACT OR FUNCTION AS, AND IS NOT IN FACT, A STAFFING, EMPLOYMENT, RECRUITMENT OR PLACEMENT AGENCY.  THE EVENTICA PLATFORM MAY BE USED BY YOU TO FACILITATE SERVICES BY AND AMONG USERS.  However, Eventica is not in any way responsible for the performance or obligations of Users, and it does not exercise control over the quality, timing, provision, legality, or any other aspect whatsoever of the Services, or any of the actions or omissions whatsoever of any User.</p>
							<h3>1.2 Eligibility</h3>
							<p align="justify">You represent, warrant and covenant that you are not (a) a citizen or resident of a country in which use or participation in the Eventica Platform or any of the Services are prohibited by law, decree, regulation, treaty or administrative act; (b) a citizen or resident of, or located in, a country or region that is subject to U.S. or other sovereign country sanctions or embargoes; or (c) an individual or an individual employed by or associated with an entity identified on the U.S. Department of Commerce’s Denied Persons or Entity List, the U.S. Department of Treasury’s Specially Designated Nationals or Blocked Persons Lists, or the Department of State’s Debarred Parties List or otherwise ineligible to receive items subject to U.S. export control laws and regulations, or other economic sanction rules of any sovereign nation.</p>
							
							<h3>1.3 Clients and Freelancers</h3>
							<p align="justify">By participating as a Client, you represent and warrant that the information you submit to us or post on the Services regarding your Project are true, accurate and complete and that you will update such information as necessary to ensure that it remains true, accurate and complete. You agree that the products and services referenced in any Project are provided to Freelancers and sold to consumers in accordance with all applicable laws and that the information contained in the Project or otherwise provided by you to Freelancer: (i) is not misleading or deceptive, (ii) is in accordance with applicable laws, (iii) will not infringe any third party right including any copyright or trademark right, any right of privacy or publicity or contain any defamation or (iv) is in conformance with the requirements of our Acceptable Use Policy set forth below. You further agree that you will pay the Freelancer the consideration set forth in the Project in accordance with the provisions of this Agreement. In addition, you represent and warrant that you will not solicit users to provide you services off the Site or otherwise circumvent any fees that are paid or would be payable to Eventica. <b>You further agree that unless you obtain the consent of any Freelancer, you will use the personal information of the Freelancer provided to you by Eventica only to communicate with and receive the services to the Freelancer, and for no other purpose.</b> You are solely responsible for the truthfulness, accuracy and completeness of a Project posting you submit and for all content contained in a Project posting. Submission of a Project posting does not obligate Eventica to make the Project posting or any of its contents available on the Services and we may remove a job posting with or without notice at any time for any reason. You agree that Eventica will not be liable to you or to any third party for any removal of a Project posting or any part thereof.</p>
							<p align="justify">By participating as a Freelancer, you represent and warrant that all of the information in your profile and any information that you provide when you apply to fulfill a Project is true, accurate and complete and that you will update such information as necessary to ensure that it remains true, accurate and complete; (ii) that you will perform the services in accordance with the information you provide.  If you are selected by a Client to perform a Project, you represent and warrant that you will perform the Project (i) in substantial accordance with the requirements set forth in the Project description on the Site, (ii) in a professional and workmanlike manner in accordance with industry standards, (iii) in compliance with applicable law, (iv) in a manner that will not infringe any third party right including any copyright or trademark right, any right of privacy or publicity or contain any defamation or (v) in any manner that breaches our Acceptable Use Policy set forth below. In addition, you represent and warrant that you will not solicit users to pay for your services off the Site or otherwise circumvent any fees that are paid or would be payable to Eventica. <b>You further agree that unless you obtain the consent of any Client, you will use the personal information of the Client provided to you by Eventica only to communicate with and provide the services to the Client, and for no other purpose.</b> You are solely responsible for the truthfulness, accuracy and completeness of your profile and any information you submit to the Site. Submission of information in response to a Project does not obligate Eventica to make your submission or any of its contents available on the Services and Eventica may remove your submission with or without notice at any time for any reason. You agree that Eventica will not be liable to you or to any third party for any removal of a posting or any part thereof.</p>
							<p align="justify">Eventica does not control the quality, safety, or legality of any aspect of the job, the ability of Freelancers to provide the services, or the ability of Clients to pay Freelancers. Each Freelancer agrees that each Client for which the Freelancer performs a Project is an intended third party beneficiary of this Agreement with respect to this Section 1.3, and therefore, each Client has the right to enforce any covenant, representation or warranty set forth herein. Each Client agrees that each Freelancer that Client engages to perform a Project is an intended third party beneficiary of this Agreement with respect to this Section 1.3, and therefore, each Freelancer has the right to enforce any covenant, representation or warranty set forth herein.</p>
							<p align="justify">With respect to any particular campaign and solely with respect to each other, each Freelancer and Client agrees that the other will not be liable for ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF DATA, LOSS OF BUSINESS OR BUSINESS OPPORTUNITY, EVEN IF SUCH DAMAGES ARE FORESEEABLE AND WHETHER OR NOT SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY THEREOF. IN NO EVENT WILL FREELANCER BE LIABLE FOR THE PROCUREMENT OF SUBSTITUTE SERVICES. With respect to any particular Project and solely with respect to each other, each Freelancer and Client agrees that the other’s MAXIMUM AGGREGATE LIABILITY FOR ANY PROJECT WILL NOT EXCEED THE TOTAL AMOUNT OF FEES RECEIVED BY THE FREELANCER FROM THE CLIENT FOR THE APPLICABLE PROJECT.</p>

							<!--Eventica general polices-->
							<h2>2. EVENTICA GENERAL POLICIES</h2>
							<h3>2.1 Accounts.</h3>
							<p align="justify">(a) In order to use certain Services, for example, to create a profile or create a Project you must: (i) register for an account with Eventica (as <b>"Account"</b>) and provide certain information about yourself as prompted by the registration form and / or (ii) connect to the Services through a Social Networking Service (as defined below) in which case we will access registration information that you authorize from the Social Networking Service. You represent and warrant that: (iii) all required registration information you submit is truthful and accurate and (iv) you will maintain the accuracy of such information. You may delete your Account at any time, for any reason, by emailing support@Eventica.com. Upon termination, we will remove your Content (as defined below) as described below. You acknowledge that you have no ownership or other property interest in your Account and that all rights in and to your Account are owned by and inure to the benefit of Eventica. Eventica reserves the right in its sole discretion to suspend or terminate your Account and refuse any and all current or future use of the Eventica Platform (or any portion thereof) at any time for any reason. You agree that Eventica will not be liable to you or to any third party for any suspension or termination of your Account or any refusal of any use of the Eventica Platform (or any portion thereof).</p>
							<p align="justify">(b) As part of the registration process you will be required to provide an email address and select a password (collectively <b>"Credentials"</b>), which you may not share with any third parties. If someone accesses the Services using your Credentials, we will rely on those Credentials and will assume that it is you or your representative who is accessing the Services. You are solely responsible for any and all use of your Credentials and all activities that occur in connection with your Credentials. We reserve the right to take any and all action, as we deem necessary or reasonable, to ensure the security of the Services and your Credentials, including terminating your access, changing your password, or requesting additional information to authorize activities related to your Credentials. You agree to immediately notify Eventica of any real or suspected unauthorized use. Eventica cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.</p>
							
							<h3>2.2 Our Technology and Content</h3>
							<p align="justify">(a) Excluding any of your Content (defined below) that you may provide, you acknowledge that (i) the Eventica Platform is and will remain the sole property of Eventica and is subject to protection under U.S. and foreign copyright laws, (ii) all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the Eventica Platform and content made available through the Eventica Platform are owned by Eventica or its licensors or suppliers, and (iii) the APIs are the confidential and proprietary information of Eventica. Eventica’s name, logo, and the product names associated with the Eventica Platform belong to Eventica (or its licensors or suppliers, where applicable), and no right or license is granted to use them by implication, estoppel or otherwise. Neither these Terms nor your access to the Eventica Platform transfers to you or any third party any rights, title or interest in or to such intellectual property rights, except for the limited access rights expressly set forth in these Terms. Eventica and its licensors and suppliers reserve all rights not granted in these Terms.</p>
							<p align="j|ustify">(b) The rights and licenses are granted to you herein are subject to the following restrictions: (i) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Eventica Platform, whether in whole or in part; (ii) you shall not frame or utilize framing techniques to enclose any trademark, logo, or other portion of the Eventica Platform (including images, text, page layout, or form); (iii) you shall not use any metatags or other "hidden text" using Eventica’s name or trademarks; (iv) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Eventica Platform; (v) you may not use any manual or automated software, devices or other processes (including but not limited to spiders, robots, scrapers, crawlers, avatars, data mining tools or the like) to "scrape" or download data from any web pages contained in the Site (except that we grant the operators of public search engines revocable permission to use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such); (vi) you shall not access the Eventica Platform in order to build a similar or competitive website, product, or service; (vii) except as expressly stated herein, no part of the Eventica Platform may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means; and (viii) you shall not remove or destroy any copyright notices or other proprietary markings contained on or in the Eventica Platform. Any unauthorized use of the Eventica Platform terminates the licenses granted by Eventica pursuant to this Agreement. Eventica makes no representation that the Eventica Platform is appropriate for use in locations other than the United States.</p>
							<p align="justify">(c) Eventica reserves the right, at any time, to modify, suspend, or discontinue the Eventica Platform (in whole or in part) with or without notice to you. You agree that Eventica will not be liable to you or to any third party for any modification, suspension, or discontinuation of the Eventica Platform or any part thereof.</p>
							<p align="justify">(d) Unless otherwise indicated, any future release, update, or other addition to functionality of the Eventica Platform shall be subject to this Agreement. You acknowledge and agree that Eventica will have no obligation to provide you with any support or maintenance in connection with the Eventica Platform. You agree that Eventica is not obligated to create or provide any corrections, updates, upgrades, bug fixes, and/or enhancements of the Eventica Platform (each an <b>"Update"</b>). However, in the event Eventica decides to offer an Update, you agree that Eventica may amend this Agreement in connection with such Update without specific notice to you and that your use of the Eventica Platform following such Update is conditioned upon your acceptance of any revised Agreement. By using the Eventica Platform following an Update, you are representing that you have reviewed the then-current version of the Terms and agree to be bound by such version. All Updates will be governed by the version of these Terms published by Eventica as of the date you use the Eventica Platform following such update.</p>
							<p align="justify">(e) In addition to reviewing these terms, you should also read our Privacy Policy located at: Eventica.com/privacy to better comprehend how we collect and use your personal information. Your use of the site and its services constitutes your agreement to our Privacy Policy.</p>

							<h3>2.3 Feedback</h3>
							<p align="justify">You agree that submission of any ideas, suggestions, documents, and/or proposals to us, including through any suggestion, feedback or forum pages (<b>"Feedback"</b>) is at your own risk and that we have no obligations (including without limitation obligations of confidentiality) with respect to such Feedback. You represent and warrant that you have all rights necessary to submit the Feedback. You hereby grant to us a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sublicensable right and license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all Feedback, and to sublicense the foregoing rights without restriction and in all media now known and later developed.</p>

							<h3>2.4 User Content Transmitted Through the Eventica Platform</h3>
							<p align="justify">(a) With respect to all content and information you submit to, or use with, the Services,  (collectively, <b>"User Content"</b> or <b>" your Content"</b>), you represent and warrant that (i) you own all right, title and interest in and to such User Content or are authorized by the owner of your Content to post your Content, (ii) that you have the right to grant to Eventica the licenses herein, (iii) that your Content does not violate our Acceptable Use Policy set forth below, and (iv) that you will not use your Content to engage in deceptive or unfair trade practices or otherwise engage in illegal activity. We are under no obligation to pre-screen your Content or the Content of any other user. Your use and/or access to the Eventica Platform via any mobile phone or other mobile device provides Eventica with additional information relating to your location, time/duration of access to the Eventica Platform and other information relating to when, where and how you accessed the Eventica Platform, and all such content obtained by Eventica from your use of the Eventica mobile application shall be deemed User Content.  You hereby grant to Eventica and its affiliated companies a nonexclusive, worldwide, royalty free, fully paid up, transferable, sub-licensable, perpetual, irrevocable license to copy, display, upload, perform, distribute, store, modify, utilize, disclose and otherwise use your User Content in connection with the operation of the Eventica Platform or the promotion, advertising or marketing thereof, in any form, medium or technology now known or later developed. In addition, and with respect to Eventica’s use or publication of a user’s personal likeness, each user hereby releases Eventica from any liability from such use or publication to the fullest extent available under applicable law.</p>
							<p align="justify">(c) You may be able to store your Content in many areas within the Services. We provide these storage capabilities as a convenience to you. You represent and warrant that that Services are not the single repository for your Content and acknowledge that you, and not Eventica, are responsible for ensuring the Content is backed up. Eventica has no responsibility or liability for the deletion or loss of any of your Content. You agree that Eventica retains the right to create reasonable limits on Eventica’s use and storage of your Content, such as limits on file size, storage space, processing capacity, and similar limits as determined by us in our sole discretion.</p>
							<p align="justify">(d) You are solely responsible for your Content and assume all risks associated with use of your Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your Content that makes you or any third party personally identifiable. Eventica makes no guarantee regarding the accuracy, currency, suitability or quality of any User Content, and we assume no responsibility for any User Content. Because you alone are responsible for your User Content, you may expose yourself to liability if, for example, your User Content violates the Acceptable Use Policy or applicable law.</p>
							<p align="justify">(e)  Each Client grants to Eventica, to the fullest extent available to Client under the law, the right to use Client’s (and Client’s clients’) corporate name and logo in press releases, marketing campaigns, and/or marketing materials and otherwise, including but not limited to posting Client (and Client’s clients’) name and logo on the Eventica Platform identifying them as Eventica’s clients.</p>
							 
							<p align="justify">(f) If you wish to remove a profile or Project listing in whole or part, you may do so through the Services or by contacting support@Eventica.com. We will comply with your request for removal as soon as practicable, subject to the following: we may continue to use information derived from your Content in accordance with our Privacy Policy and we may retain the Content in a non-production environment to comply with laws, prevent fraud, resolve disputes, troubleshoot problems, assist with any investigations, enforce this Agreement, and take any other action otherwise permitted by law. Notwithstanding any such removal, the licenses set forth in Section 2.1(a) above will not be terminated for any uses of your Content within the scope of such licenses prior to the date you removed the Content.</p>
							<p align="justify">(g) The Eventica Platform may contain User Content provided by other users or third parties. We are not responsible for and do not control such content. We have the right, but no obligation to review or monitor such content. We do not approve, endorse or make any representations or warranties with respect to such content. You use all such contact at your own risk.</p>
							
							<h3>2.5 Identity and Account Security</h3>
							<p align="justify"> Eventica reserves the right to validate your information at any time, including but not limited to validation against third party databases or the verification of one or more official government or legal documents that confirm your identity. You authorize Eventica, directly or through third parties, to make any inquiries necessary to validate your identity and confirm your ownership of your email address or financial accounts. Failure to provide information about you and your business when requested is a violation of this Agreement. You are solely responsible for ensuring and maintaining the secrecy and security of your Eventica account password. You agree not to disclose this password to anyone and will be solely responsible for any use of or action taken through the use of such password on Eventica. You must notify Eventica support immediately if you suspect that your password has been lost or stolen. By using your Eventica account, you acknowledge and agree the Eventica’s account security procedures are commercially reasonable.</p>

							<h3>2.6 Acceptable Use Policy.</h3>
							<p align="justify">(a) <i>Unauthorized Actions</i>. You agree that you will not access (or attempt to access) the Eventica Platform by any means other than the interface provided, and you will not use the Eventica Platform, or any information obtained from the Eventica Platform, for any purpose other than the purpose for which it was made available to you. You are solely responsible for all of your User Content, including but not limited to code, video, images, information, data, text, software, music, sound, photographs, graphics, messages or other materials, that you upload, post, publish, display, email or otherwise use or distribute via the Eventica Platform. Eventica reserves the right to investigate and take appropriate legal action against anyone who, in Eventica’s sole discretion, violates this provision.</p>
							<p align="justify">In addition, and not by way of limitation, you expressly agree that you will not use the Eventica Platform to:</p> 
							<ul>
                            <li>upload or transmit any content that (A) infringes any intellectual property or other proprietary rights of any party; (B) you do not have a right to upload or transmit under any law or under contractual or fiduciary relationships; (C) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; (D) poses or creates a privacy or security risk to any person; (E) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, "junk mail," "spam," "chain letters," "pyramid schemes," "contests," "sweepstakes," or any other form of solicitation; (F) is unlawful, harmful, threatening, abusive, harassing, tortious, excessively violent, defamatory, vulgar, obscene, pornographic, libelous, invasive of another’s privacy, hateful racially, ethnically or otherwise objectionable; or (G) in the sole judgment of Eventica, is objectionable or which restricts or inhibits any other person from using or enjoying the Eventica Platform, or which may expose Eventica or its users to any harm or liability of any type;
                            </li>
                            
							<li>interfere with or disrupt the Eventica Platform or servers or networks connected to the Eventica Platform, or disobey any requirements, procedures, policies or regulations of networks connected to the Eventica Platform;</li>
							<li>violate any applicable local, state, national or international law, or any regulations having the force of law;</li>
							<li>disclose information that constitutes material, non-public information about any third party that you have a duty or obligation to keep confidential (whether by agreement, law, rule, regulation, fiduciary duty, or other similar obligation or restriction) or any information the disclosure of which would be in violation of securities laws and/or information that is proprietary to a third party (including past or present employers or companies for which you have consulted) and not owned solely by you;</li>
							<li>impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
							<li>solicit personal information from anyone under the age of 18, and for any personal information lawfully solicited use such information strictly in connection with your lawful use of the Eventica Platform;</li>
							<li>harvest or collect email addresses or other contact information or User Content of other users from the Eventica Platform by electronic or other means for purposes of sending unsolicited emails or other unsolicited communications or solicitations;</li>
							<li>advertise or offer to sell or buy any goods or services for any business purpose that is not specifically authorized by Eventica;</li>
							<li>further or promote any criminal or unlawful activity or enterprise or provide instructional information about illegal activities;</li>
							<li>disclose to any third party or use for any purpose other than the purpose for which it was made available any information of Eventica marked as "confidential" or "proprietary"; or</li>
							<li>obtain or attempt to access or otherwise obtain any materials or information through any means not expressly authorized or intentionally provided for through the Eventica Platform.</li>
</ul>
							<p align="justify">(b) <i>No Reverse Engineering.</i> The technology and software underlying the Eventica Platform or distributed in connection therewith (the <b>"Software"</b>) is the property of Eventica, our affiliates and our partners. You agree that you will not copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, or otherwise transfer any right in the Software. Any rights not expressly granted herein are reserved by Eventica.</p>
							<p align="justify">(c) <i>Enforcement of Agreement and Policies.</i> Eventica retains the right, but not the obligation, to monitor your use of the Eventica Platform, any User Content that you upload or transmit and the Services performed by the Freelancer on any Project to determine your or any other user’s compliance with the terms and conditions of this Agreement and to suspend or cancel your access to the Eventica Platform if it believes that you have violated or acted inconsistently with the letter or spirit of this Agreement or violated Eventica’s rights or those of another party. Without limiting Eventica’s other remedies, it may suspend or terminate your account, use self-help in connection with its rights to reclaim any available funds, and refuse to provide any further access to the Eventica Platform to you if (a) you breach any terms and conditions of this Agreement or other written policies and procedures posted on the Eventica Platform; (b) we are unable to verify or authenticate any information you provide to us; or (c) we believe that your actions may cause legal liability for you, our other users or for Eventica. Once suspended or terminated, you MAY NOT continue to use the Eventica Platform under a different account or reregister under a new account. If you attempt to use the Eventica Platform under a different account, we reserve the right to reclaim available funds in that account and/or use an available payment method to pay for any amounts outstanding. In addition, violations of this Agreement may be prosecuted to the fullest extent of the law and may result in additional penalties and sanctions. When your account is canceled, you may no longer have access to any parts of the Eventica Platform, including data, messages, files and other material you keep on Eventica, including but not limited to User Content.</p>

							<!--Payment terms, invoices and payment methods-->
							<h2>3. PAYMENT TERMS, INVOICES AND PAYMENT METHODS</h2>
							<h3>3.1 Eventica Fees</h3>
							<p align="justify">Eventica receives a fee from Clients for creating, hosting, maintaining and providing the Eventica Platform, for facilitating the connection between Client and Freelancer(s) and for facilitating payment of any agreed fee between a Client and a Freelancer for the Services performed.  Such fees (the <b>"Eventica Fees"</b>) are payable by Client and subject to the terms of this Agreement (including the Standard Project Terms (defined below)).</p>

							<h3>3.2 Disbursements to Freelancers</h3>
							<p align="justify">Eventica will remit Client payment funds to Freelancers consistent with the Standard Project Terms (defined below), any specific terms contained in a Project, and otherwise consistent with Eventica’s practices. Funds become payable to Freelancers only upon all of the following occurring:  (a) Freelancer accepts a Project and fully performs requested Services from a Client; (b) Client accepts Freelancer’s performed Services; and (c) Client remits appropriate payment to Eventica.  Payments facilitated by Eventica to Freelancers shall be performed by Eventica as Client’s limited payment agent solely for the facilitation of payment for Freelancer’s Services and such payment shall be considered the same as payment made directly by Client to Freelancer.</p>

							<h3>3.3 Payment</h3>
							<p align="justify">All payment information that you provide in connection with the Services must be accurate, current and complete. YOU REPRESENT AND WARRANT THAT YOU HAVE THE LEGAL RIGHT TO USE ANY PAYMENT CARD(S) OR OTHER PAYMENT MEANS USED TO PAY ANY FEE OR CHARGE. By providing Eventica with your payment information, you agree that Eventica or a third party payment service provider is authorized to immediately invoice you for all fees and charges due and payable to Eventica hereunder and that no additional notice or consent is required. You agree to immediately notify Eventica of any change to your payment information. Eventica reserves the right at any time to change its prices and billing methods, either immediately upon posting on the Eventica Platform or by e-mail delivery to you.</p>

							<h3>3.4 Non-Payment</h3>
							<p align="justify">If Client fails to accept any Services performed by a Freelancer, or otherwise fails to pay amounts due under this Agreement, whether by cancelling Client’s payment method, initiating an improper chargeback or any other means, Client’s Eventica Account may be suspended, additional payments may be curtailed or terminated, and Client’s access to the Eventica Platform may be immediately stopped. Without limiting other available remedies, Client will reimburse Eventica for amounts due upon demand, plus any applicable processing fees, charges or penalties, plus interest at the lesser of one and one-half percent (1.5%) per month or the maximum allowed by law, plus attorneys’ fees and other costs of collection as allowed by law. In its discretion, Eventica may setoff amounts due against other amounts received from, make appropriate reports to credit reporting agencies and law enforcement authorities, and cooperate with them in any resulting investigation or prosecution.</p>

							<h3>3.5 Client Non-circumvention</h3>
							<p align="justify">Client will make all payments relating to, or in any way connected with a Project through the Eventica Platform. Any action that encourages or solicits complete or partial payment outside of the Eventica Platform is a violation of this Agreement.</p>
							<p align="justify">For clarity, you are agreeing to not circumvent the payment facilitation methods offered by the Eventica Platform for any particular Project. By way of illustration and not in limitation of the foregoing, you agree not to:</p>
							<p align="justify">(a) Submit proposals to, solicit, contract, hire, manage or pay any Freelancers identified for a particular Project through the Eventica Platform except through the Eventica Platform for that particular Project;</p>
							<p align="justify">(b) Accept proposals from, contact, deliver services to, invoice or receive payments from parties identified through the Eventica Platform other than through the Eventica Platform, or otherwise in accord with the ongoing provision of Services through the Eventica Platform; or</p>
							<p align="justify">(c) Invoice or report on the Eventica Platform for a particular Project an invoice or payment amount lower than that actually agreed between Client and Freelancer through the Eventica Platform for that particular Project.</p>
							<p align="justify">YOU WILL NOTIFY EVENTICA IMMEDIATELY IF ANOTHER PERSON IMPROPERLY CONTACTS YOU OR SUGGESTS MAKING OR RECEIVING PAYMENTS OUTSIDE OF THE EVENTICA PLATFORM. If you are aware of a breach or potential breach of this non-circumvention policy, please submit a confidential report to Eventica by sending an email message to: support@Eventica.com.</p>

							<h3>3.6 Taxes; Tax Reporting</h3>
							<p align="justify">You will be responsible for paying any applicable taxes relating to your payments and credits received and will indemnify and hold harmless Eventica and its third party payment service provider from any and all taxes, including sales tax, based on any payments made or received by you in connection with the Services. Any taxes imposed on payments will be your sole responsibility. Upon our request, you will provide Eventica with official receipts issued by the appropriate taxing authority, or other such evidence that you have paid all applicable taxes.</p>
							<p align="justify">No matter who makes the payment directly to Freelancer, Client, not Eventica, is responsible to pay all taxes associated with the Freelancer’s performance of the Project including all sales and use taxes and to file appropriate forms with the appropriate taxing authorities (e.g., Form W2). Freelancers are independent contractors of Client and are not employees of Eventica or Client.</p>

							<h3>3.7 Payment Methods</h3>
							<p align="justify">Unless otherwise agreed between Client and Eventica, all Client payments to Eventica shall be made by company check, cashier’s check, certified check or electronic transfer.</p>
							
							<!--Standar project terms between client and frellancer-->
							<h2>4. STANDARD PROJECT TERMS BETWEEN CLIENT AND FREELANCER</h2>
							<p align="justify">Unless otherwise agreed to by Eventica, the Standard Project Terms (<b>"SPT"</b>) contained in this Section 4 shall apply to any Services provided by Freelancer to Client on Events.</p>
							<p align="justify">Client and Freelancer may agree on Project-specific terms and conditions as may be set forth in an applicable Project posting.  Notwithstanding the foregoing, Client and Freelancer may not agree to any other terms and conditions that affect the rights or responsibilities of Eventica as described herein without Eventica’s express written consent and the terms and conditions contained in this Agreement shall control in the event of any conflict with any Project-specific terms and conditions.  Without limitation, users expressly agree that by using the Eventica Platform, all users acknowledge that a Freelancer’s relationship with Eventica is limited to that of a licensee to use the Eventica Platform as described herein.  The relationship between Freelancers and Clients is governed by the terms of this Agreement, the SPT and any additional terms and conditions for a particular Project.  Under no circumstances will a Freelancer be deemed an independent contractor or employee of Eventica.</p>

							<!--Your acnowledent-->
							<h2>5. YOUR ACKNOWLEDGMENT OF EVENTICA’S ROLE</h2>
							<h3>5.1 Eventica’s Role</h3>
							<p align="justify">You expressly acknowledge, agree and understand that: (i) the Eventica Platform is a technology platform through which users may act as either Clients or Freelancers; (ii) Eventica does not hire or retain any Freelancer and only hosts and maintains the Eventica Platform to facilitate the communications and payment from Client to Freelancer; (iii) Eventica is not a direct party to any agreement between Clients and Freelancers; (iii) each Freelancer acknowledges and agrees that such Freelancer is not an employee, agent or partner of Eventica and that Eventica does not, in any way, supervise, direct, or control a Freelancer’s work or Services; (iv) Eventica will not have any liability or obligations under or related to Events for any acts or omissions by a user; (v) Eventica has no control over Freelancers or over the Services promised or rendered on a Project by Freelancers; and (vi) Eventica makes no representations as to the reliability, capability, or qualifications of any Freelancer or the quality, security or legality of any Services, and Eventica disclaims any and all liability relating thereto.</p>
							<p align="justify">Eventica does not directly introduce Freelancers to Clients or directly help Freelancers find Events.  However, Eventica does provide an online, electronic platform, including certain search tools and automatic notifications that may facilitate introductions to Clients and identification of Events.</p>
							<p align="justify">Eventica makes the Eventica Platform available to enable Freelancers, in their discretion, to identify and determine the suitability of Events and Clients for themselves, and to enable Clients, in their discretion, to identify and determine the suitability of Freelancers for themselves. Eventica does not direct, has no control over, makes no representations, and does not guarantee the quality, safety or legality of Services advertised or provided, the truth or accuracy of Project listings, the qualifications, background, or identities of users, the ability of Freelancers to deliver Services, the ability of Clients to pay for Services, or that a Client or Freelancer can or will actually complete a Project.</p>

							<h3>5.2 Background Checks</h3>
							<p align="justify">Eventica is not required to and does not verify any information given to us by Freelancers or Clients.  Although not required, Eventica reserves the right to perform background checks on Freelancers or Clients for identity verification and other background checks on users, at the Country, State and local level, using third party services as appropriate.  Although Eventica reserves the right, but not the obligation, to perform the foregoing background checks of users, Eventica cannot confirm that each user is who they claim to be and Eventica does not assume any responsibility for the accuracy or reliability of the identity or background check information of any user.</p>
							<p align="justify">Eventica may also facilitate the provision of additional information about a Freelancer or Client, such as a strength or risk score, geographical location or third party feedback, background check or verification of identity or credentials, or specific Freelancer attributes. However, such information is based solely on User Content that Freelancer or Client submits and Eventica provides such information solely for the convenience of the Users and not as an introduction, endorsement or recommendation by Eventica.</p>

							<h3>5.3 Other Users</h3>
							<p align="justify">Each user of the Eventica Platform is solely responsible for any and all of its own User Content. Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, whether provided by you or by others. We make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content. Your interactions with other users of the Eventica Platform are solely between you and such users. You agree that Eventica will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any user of the Eventica Platform, we are under no obligation to become involved.</p>

							<h3>5.4 Third Party Websites</h3>
							<p align="justify">The Eventica Platform may provide, or third parties may provide, links or other access to other sites and resources on the Internet.  Eventica has no control over such sites and resources and Eventica is not responsible for and does not endorse such sites and resources. You further acknowledge and agree that Eventica will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods or services available on or through any such site or resource. Any dealings you have with third parties found while using the Eventica Platform are between you and the third party, and you agree that Eventica is not liable for any loss or claim that you may have against any such third party.</p>

							<h3>5.5 Social Networking Services</h3>
							<p align="justify">You may enable access to various online third party services through the Eventica Platform, such as social media and social networking services like LinkedIn (each a <b>"Social Networking Service"</b>). By logging in or directly integrating these Social Networking Services into the Eventica Platform, we make your online experiences richer and more personalized. To take advantage of these features and capabilities, we may ask you to authenticate, register for or log into Social Networking Services on the websites of their respective providers. As part of such integration, the Social Networking Services will provide us with access to certain information that you have provided to such Social Networking Services, and we will use, store and disclose such information in accordance with our Privacy Policy. For more information about the implications of activating these Social Networking Services and Eventica’s use, storage and disclosure of information related to you and your use of such services within Eventica, please see our Privacy Policy. However, please remember that the manner in which Social Networking Services use, store and disclose your information is governed solely by the policies of such third parties, and Eventica will have no liability or responsibility for the privacy practices or other actions of any third party site or service that may be enabled within the Eventica Platform.</p>
							<p align="justify">Eventica is not responsible for the accuracy, availability or reliability of any information, content, goods, data, opinions, advice or statements made available in connection with Social Networking Services. As such, Eventica is not liable for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Social Networking Services. Eventica enables these features merely as a convenience and the integration or inclusion of such features does not imply an endorsement or recommendation.</p>

							<h3>5.6 No Agency</h3>
							<p align="justify">Your relationship to Eventica is that of an independent contractor.</p>
							<p align="justify">This Agreement and any registration for or use of the Eventica Platform will not be construed as creating or implying any relationship of agency, franchise, partnership or joint venture between you and Eventica.</p>

							<h3>5.7 Text Messaging and Mobile Phone Use</h3>
							<p align="justify">By creating an Account on the Eventica Platform, you agree that the Eventica Platform may send you informational text (SMS) messages as part of the normal business operation of your use of the Eventica Platform (the <b>"Text Services"</b>) and are expressly consenting thereto.  You may opt-out of receiving text (SMS) messages from Eventica at any time by texting Eventica the word STOP from the mobile device receiving the messages.  You acknowledge that opting out of receiving text (SMS) messages may impact your use of the Eventica Platform.  If you need help regarding the Text Services, email support@Eventica.com. We do not charge a fee for the Text Services; however, depending on your messaging plan, your mobile carrier may charge you for each message we send you or that you send us. It is your responsibility to know whether your carrier will charge you per-message costs (for instance, if you do not have an unlimited texting plan, or have exceeded your monthly quota of free messages). We assume no responsibility for charges incurred by your using the Text Services. The Text Services may not be available in all areas at all times. This means we may not be able to successfully transmit SMS/MMS messages to you, and we have no liability for any such transmission delay or message failure. The Text Services may not work in the event of product, software, coverage, or other changes made by your wireless carrier or changes you make to your mobile device. You must provide your own wireless device, subscribe to a wireless service on a participating mobile carrier, and be able to receive text messages using that wireless device and your carrier’s service.</p>

							<h3>5.8 Third-Party Services and Content</h3>
							<p align="justify">The Services may be made available or accessed in connection with third-party services and content (including advertising) that Eventica does not control.  You acknowledge that different terms of use and privacy policies may apply to your use of such third-party services and content.  Eventica does not endorse such third party services and content and in no event shall Eventica be responsible or liable for any products or services of such third party providers.</p>
							<p align="justify">You acknowledge and agree that the availability of the App is dependent on the App Store from which you received the App. You and Eventica acknowledge that these Terms are between you and Eventica and not with the App Store and that Eventica, and not the App Store, is responsible for the App and the content thereof. Eventica is responsible for providing any maintenance and support services with respect to the App and the App Store has no obligation whatsoever to furnish any maintenance and support services with respect to the App. Eventica is solely responsible for any product warranties, whether express or implied by law, to the extent not effectively disclaimed. In the event of any failure of the App to conform to any applicable warranty, you may notify the App Store, and the App Store may refund the purchase price for the App to you; and to the maximum extent permitted by applicable law, the App Stores will not have any other warranty obligation whatsoever with respect to the App, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be Eventica’s sole responsibility. You and Eventica acknowledge that Eventica, and not the App Store, is responsible for addressing any claims relating to the App or your possession and/or use of that App, including, but not limited to: (1) product liability claims; (2) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (3) claims arising under consumer protection or similar legislation. You and Eventica acknowledge that, in the event of any third party claim that the App infringes or your possession and use of that App that third party’s intellectual property rights, Eventica, and not the App Store, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim. You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You agree to comply with, and your license to use the App is conditioned upon your compliance with, all applicable third party terms of agreement (e.g., the App Store’s terms and policies and the Usage Rules) when using the App. Eventica and you acknowledge and agree that the App Stores and their subsidiaries, are third party beneficiaries of these Terms, and that, upon your acceptance of the terms and conditions of these Terms, the App Stores will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary thereof.</p>

							<h3>5.9 Promotional Codes</h3>
							<p align="justify">Eventica may, in its sole discretion, create promotional codes that may be redeemed for credit or other features or benefits related to a third party provider’s services, subject to terms that Eventica establishes on a per promotional code basis (<b>"Promo Codes"</b>).   You agree that Promo Codes:  (i) must be used for the intended audience and purpose, and in a lawful manner; (ii) may not be duplicated, sold or transferred in any manner, or made available to the general public, unless expressly permitted by Eventica; (iii) may be disabled by Eventica at any time for any reason without liability to Eventica; (iv) may only be used pursuant to the specific terms that Eventica establishes for such Promo Code; (v) are not valid for cash; and (vi) may expire prior to your use.  Eventica reserves the right to withhold or deduct credits or other features or benefits obtained through the use of Promo Codes by you or any other user in the event that Eventica determines or believes that the use or redemption of the Promo Code was in error, fraudulent, illegal, or in violation of the applicable Promo Code terms, or this Agreement.</p>

							<h3>5.10 Release</h3>
							<p align="justify">You hereby release and forever discharge the Eventica (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or that relates directly or indirectly to: (a) the Eventica Platform (including any interactions with, or act or omission of, other users of the Eventica Platform or any third party links, websites and content); (b) any inaccurate, incomplete, unreliable, illegal or infringing User Content posted on the Services, whether caused by us or any user of the Services, or by any of the equipment or programming associated with or utilized in the Services; (c) the conduct, whether online or offline, of any user; (d) any injury, loss or damage caused by another user or User Content posted on the Services, whether online or offline; and (e) any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, the Services’ users’ communications. IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR."</p>

							<!--Discalaimers-->
							<h2>6. DISCLAIMERS</h2>
							<p align="justify">OU EXPRESSLY ACKNOWLEDGE AND AGREE THAT YOUR USE OF THE EVENTICA PLATFORM IS AT YOUR SOLE RISK AND THAT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EVENTICA AND OUR LICENSORS AND SUPPLIERS MAKE NO WARRANTIES REGARDING THE USERS OR THE EVENTICA PLATFORM, INCLUDING THE EVENTS OR OTHER INFORMATION MADE AVAILABLE THROUGH THE SERVICES OR THE INTERACTIONS BETWEEN THE USERS WITHIN OR OUTSIDE OF THE SITE, AND EACH OF THE FOREGOING IS PROVIDED ON AN "AS-IS" AND "AS AVAILABLE" BASIS, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND EVENTICA AND OUR LICENSORS AND SUPPLIERS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE USERS OR THE EVENTICA PLATFORM, INCLUDING THE EVENTS OR OTHER INFORMATION MADE AVAILABLE THROUGH THE SERVICES OR THE INTERACTIONS BETWEEN THE USERS WITHIN OR OUTSIDE OF THE SITE, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT. EVENTICA AND OUR LICENSORS AND SUPPLIERS MAKE NO WARRANTY THAT THE EVENTICA PLATFORM WILL MEET YOUR REQUIREMENTS, WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS, OR WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE, OR THAT DEFECTS IN THE EVENTICA PLATFORM WILL BE CORRECTED. IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE EVENTICA PLATFORM, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO NINETY (90) DAYS FROM THE DATE OF FIRST USE. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY EVENTICA OR ITS AUTHORIZED REPRESENTATIVES WILL CREATE A WARRANTY. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.</p>

							<!--Limitation of libility-->
							<h2>7. LIMITATION OF LIABILITY</h2>
							<p align="justify">TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL EVENTICA (OR OUR SUPPLIERS OR LICENSORS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFITS, LOST DATA, COSTS OF PROCUREMENT OF SUBSTITUTE PRODUCTS, OR ANY SPECIAL, CONSEQUENTIAL, INCIDENTAL, EXEMPLARY OR INDIRECT COSTS OR DAMAGES ARISING FROM OR RELATING TO THIS AGREEMENT OR YOUR USE OF, OR INABILITY TO USE, THE EVENTICA PLATFORM.  ACCESS TO, AND USE OF, THE EVENTICA PLATFORM IS AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR DEVICE OR COMPUTER SYSTEM, OR LOSS OF DATA RESULTING THEREFROM. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE MAXIMUM LIABILITY OF EVENTICA (AND OUR SUPPLIERS AND LICENSORS) TO ANY USER FOR ANY CLAIM ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT SHALL NOT EXCEED THE GREATER OF THE AMOUNT OF EVENTICA FEES RECEIVED BY EVENTICA WITH RESPECT TO EVENTS ON WHICH YOU WERE INVOLVED AS CLIENT OR FREELANCER DURING THE SIX (6) MONTH PERIOD PRECEDING THE DATE OF THE CLAIM AND FIFTY US DOLLARS (U.S. $50). THESE LIMITATIONS WILL APPLY TO ANY LIABILITY, ARISING FROM ANY CAUSE OF ACTION WHATSOEVER, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH COSTS OR DAMAGES AND EVEN IF THE LIMITED REMEDIES PROVIDED HEREIN FAIL OF THEIR ESSENTIAL PURPOSE. YOU AGREE THAT OUR SUPPLIERS AND LICENSORS WILL HAVE NO LIABILITY OF ANY KIND ARISING FROM OR RELATING TO THIS AGREEMENT.</p>
							<p align="justify">SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.   THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN EVENTICA AND YOU.</p>

							<!--Indemnification-->
							<h2>8. INDEMNIFICATION</h2>
							<p align="justify">You hereby agree to indemnify, defend and hold harmless Eventica and its subsidiaries, affiliates, officers, directors, owners, employees, representatives, attorneys and agents (each, an "Indemnified Party") from any and all claims, actions, damages, liabilities, costs, and expenses (including, but not limited to, reasonable attorneys’ fees and all related costs and expenses) arising from or relating to your use of, or inability to use, the Eventica Platform, provision or receipt of Services on a Project, your User Content, your violation of these Terms of Service, your violation of any rights of another party, including any users, and your interaction with any other user.  This section expressly includes, without limitation, claims that Freelancer was misclassified as a licensee or  independent contractor or that Eventica was an employer or joint employer of a Freelancer, as well as claims under any employment-related laws, such as those relating to employment termination, employment discrimination, harassment or retaliation, as well as any claims for overtime pay, sick leave, holiday or vacation pay, retirement benefits, worker’s compensation benefits, unemployment benefits, or any other employee benefits. Eventica reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims.  You agree not to settle any matter without the prior written consent of Eventica.  Eventica will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>

							<!--Term and termination-->
							<h2>9. TERM AND TERMINATION</h2>
							<h3>9.1 Term</h3>
							<p align="justify">The term of this Agreement commences on the date of acceptance of this Agreement and continues in effect while you use the Eventica Platform.</p>

							<h3>9.2 Termination</h3>
							<p align="justify">You may terminate your Account at any time, for any reason, by following the instructions on the Site or uninstalling the App.  We may suspend or terminate your rights to use the Eventica Platform (including your Account) at any time for any reason at our sole discretion, including for any use of Eventica Platform in violation of this Agreement.</p>

							<h3>9.3 Consequences of Termination</h3>
							<p align="justify">Upon termination of your rights under this Agreement, your Account and right to access and use Eventica Platform will terminate immediately.  You understand that any termination of your Account may involve deletion of your User Content associated with your Account from our live databases.  Eventica will not have any liability whatsoever to you for any termination of your rights under this Agreement, including for termination of your Account or deletion of your User Content.  Even after your rights under this Agreement are terminated, all provisions of this Agreement which by their nature should survive, will survive, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability.</p>
							
							<!--General-->
							<h2>10. GENERAL</h2>
							<h3>10.1 Entire Agreement</h3>
							<p align="justify">This Agreement sets forth the entire agreement and understanding of the parties relating to its subject matter and cancels and supersedes any prior or contemporaneous discussions, agreements, representations, warranties, and other communications between them. The Section titles in this Agreement are for convenience only and have no legal or contractual effect. The word "including" means "including without limitation."</p>

							<h3>10.2 Side Agreements</h3>
							<p align="justify">Section 10.1 above notwithstanding, Clients and Freelancers may enter into any supplemental or other written agreement that they deem appropriate, provided that no such agreement shall alter the terms and conditions set forth in this Agreement without Eventica’s written consent. The terms and conditions of this Agreement will govern and supersede any term or condition in a side agreement that purports to expand Eventica’s obligations or restrict Eventica’s rights under this Agreement.</p>

							<h3>10.3 Compliance</h3>
							<p align="justify">You will not violate any laws or third party rights on or related to the Eventica Platform. Without limiting the generality of the foregoing, you agree to comply with all applicable import and export control laws and third parties’ Proprietary Rights. The transmission of applicable data, if any, is subject to United States export controls. Using the Eventica Platform is at your sole risk. Recognizing the global nature of the Internet, you agree to comply with all local rules and laws regarding your use of the Eventica Platform, including as it concerns online conduct and acceptable content.</p>

							<h3>10.4 Notices; Consent to Electronic Notice</h3>
							<p align="justify">You consent to the use of (a) electronic means to complete this Agreement and to deliver any notices pursuant to this Agreement; and (b) electronic records to store information related to this Agreement or your use of the Eventica Platform. Notices hereunder will be invalid unless made in writing and given (a) by Eventica via email (in each case to the email address that you provide), (b) a posting on the Eventica Platform or (c) by you via email to <a href="http://www.support@Eventica.com ">support@Eventica.com</a> or to such other addresses as Eventica may specify in writing. The date of receipt will be deemed the date on which such notice is transmitted.</p>

							<h3>10.5 Modifications</h3>
							<p align="justify">No modification or amendment to this Agreement will be binding upon Eventica unless in a written instrument signed by a duly authorized representative of Eventica. For the purposes of this Section 10.5, a written instrument will expressly exclude electronic communications such as email and electronic notices but will include facsimiles.</p>

							<h3>10.6 No Waiver</h3>
							<p align="justify">Our failure to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision.</p>

							<h3>10.7 Assignability</h3>
							<p align="justify">You may not assign this Agreement, or any of its rights or obligations hereunder, without Eventica’s prior written consent in the form of a written instrument signed by a duly authorized representative of Eventica (and, for the purposes of this Section 10.7, a written instrument will expressly exclude electronic communications such as email and electronic notices but will include facsimiles). Eventica may freely assign this Agreement without your consent. Any attempted assignment or transfer in violation of this Section will be null and void. Subject to the foregoing restrictions, this Agreement will inure to the benefit of the successors and permitted assigns of the parties.</p>

							<h3>10.8 Severability</h3>
							<p align="justify">If and to the extent any provision of this Agreement is held illegal, invalid, or unenforceable in whole or in part under applicable law, such provision or such portion thereof will be ineffective as to the jurisdiction in which it is illegal, invalid, or unenforceable to the extent of its illegality, invalidity, or unenforceability, and will be deemed modified to the extent necessary to conform to applicable law so as to give the maximum effect to the intent of the parties. The illegality, invalidity, or unenforceability of such provision in that jurisdiction will not in any way affect the legality, validity, or enforceability of such provision in any other jurisdiction or of any other provision in any jurisdiction.</p>

							<h3>10.9 Choice of Law</h3>
							<p align="justify">This Agreement and any controversy, dispute or claim arising out of or relating to this Agreement, will be governed by and construed in accordance with the laws of the State of Illinois, without regard to its conflict of law provisions and excluding the United Nations Convention on Contracts for the International Sale of Goods (CISG).</p>

							<h3>10.10 Personal Jurisdiction and Venue</h3>
							<p align="justify">You agree that any claim you may have against Eventica must be resolved by the state or Federal courts located in Cook County, Illinois. You hereby irrevocably consent to the personal jurisdiction and venue of these courts.</p>

							<h3>10.11 Prevailing Language</h3>
							<p align="justify">The English language version of this Agreement will be controlling in all respects and will prevail in case of any inconsistencies with translated versions, if any.</p>

							<h3>10.12 Copyright/Trademark Information</h3>
							<p align="justify">Copyright © 2015 Eventica. All rights reserved. All trademarks, logos and service marks (<b>"Marks"</b>) displayed on the Eventica Platform are our property or the property of other third parties. You are not permitted to use these Marks without our prior written consent or the consent of such third party which may own the Marks.</p>

							<h3>10.13 Force Majeure</h3>
							<p align="justify">Eventica shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, war, terrorism, riots, embargos, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation facilities, fuel, energy, labor or materials.</p>
							
							<!--Notice for california users-->
							<h2>11. NOTICE FOR CALIFORNIA USERS</h2>
							<p align="justify">Under California Civil Code Section 1789.3, users of the Eventica Platform from California are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 North Market Blvd., Suite N 112, Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210.</p>

							<!--Copyright policy-->
							<h2>12. COPYRIGHT POLICY</h2>
							<p align="justify">Eventica respects the intellectual property of others and asks that users of the Eventica Platform do the same. In connection with the Eventica Platform, we have adopted and implemented a policy respecting copyright law that provides for the removal of any infringing materials and for the termination, in appropriate circumstances, of users of the Eventica Platform who are repeat infringers of intellectual property rights, including copyrights. If you believe that one of our users is, through the use of the Eventica Platform, unlawfully infringing the copyright(s) in a work, and wish to have the allegedly infringing material removed, the following information in the form of a written notification (pursuant to 17 U.S.C. § 512(c)) must be provided to our designated Copyright Agent:</p>
							<p align="justify">
								1. Your physical or electronic signature;</br>
								2. identification of the copyrighted work(s) that you claim to have been infringed;</br>
								3. identification of the material on our services that you claim is infringing and that you request us to remove;</br>
								4. sufficient information to permit us to locate such material;</br>
								5. your address, telephone number, and e-mail address;</br>
								6. a statement that you have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law; and</br>
								7. a statement that the information in the notification is accurate, and under penalty of perjury, that you are either the owner of the copyright that has allegedly been infringed or that you are authorized to act on behalf of the copyright owner.
							</p>
							<p align="justify">Please note that, pursuant to 17 U.S.C. § 512(f), any misrepresentation of material fact (falsities) in a written notification automatically subjects the complaining party to liability for any damages, costs and attorney’s fees incurred by us in connection with the written notification and allegation of copyright infringement.</p>
							
							<!--Contac information-->
							<h2>13. CONTACT INFORMATION</h2>
							<p align="justify">Eventica’s contact information for any end-user questions, complaints or claims with respect to the Eventica Platform is: support@Eventica.com.</p>

							<!--Changes-->
							<h2>14. CHANGES</h2>
							<p align="justify">This Agreement subject to occasional revision. We will notify you of any changes to this Agreement by posting the new Terms here: Eventica.com/terms. After we make the change and we will change the "Last Updated" date above. If we make any substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us (if any), and/or by prominently posting notice of the changes on the Eventica Platform. You are responsible for providing us with your most current e-mail address. In the event that the last e-mail address that you have provided us is not valid, or for any reason is not capable of delivering to you the notice described above, our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice. Any changes to this Agreement will be effective upon the earlier of thirty (30) calendar days following our dispatch of an e-mail notice to you (if applicable) or thirty (30) calendar days following our posting of notice of the changes on the Eventica Platform. These changes will be effective immediately for new users of our Eventica Platform. Continued use of Eventica Platform following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.</p>

							</div>
					</div>
				</div>
			</div>
		</div>
		<footer id="footer" style="background-color:#293440;">
			
			<section style="background-color:#181e25;">
				<div class="row" style="background-color:#181e25;">
					<div class="large-4 columns" style="color:white;margin-top:25px;" align="center">
						<span class="nowrap"><b>&copy; 2015</b></span>
						<span class="nowrap">Eventica.</span>
					</div>
					<div class="large-4 columns" style="margin-top:25px;" align="center">
						<nav class="menu">
							<ul>
								<li style="color:white;">|</li>
								<li><a style="color:white;" href="contact.php">Contact</a></li>
								<li><a style="color:white;" href="comming.php">Sign Up</a></li>
								<li style="color:white;">|</li>
							</ul>
						</nav>
					</div>
					<div class="large-3 columns" style="color:white;margin-top:25px;"  align="center">
						<a style="color:#fff;" href="terms.php">Terms</a>|<a style="color:#fff;" href="privacy.php">Privacy</a>
					</div>
				</div>
			</section>
		</footer>
		<!-- Javascript -->
		<script src="js/proyecto.js"></script>
		<script src="js/jquery.js"></script>
	<script src="js/jquery.backstretch.min.js"></script>
	<script src="js/jquery.countdown.js"></script>
	<script src="js/col_footer.js"></script>
	
	
	</body>
	
	</html>
	
		